# Site settings
title: Artists Theme
email: artist@email.com
description: Thinker // Designer // Youtuber


# Change the site default images and content here
bg-img:  hero-bg.jpg
logo: logo.svg
avatar: travitar.jpg
blurb: <p><strong>Travis specializes in making things</strong> for human people. Most of the things he makes are <a href="http://travisneilson.com">digital interfaces</a>, but he also puts effort into crafting <a href="http://soundcloud.com/travis-neilson">next-level beats</a> and YouTube videos abpout making codes happen.</p>


# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested