# Site settings
title: Artists Theme
email: artist@email.com
description: Thinker // Designer // Youtuber


# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested